#!/bin/bash

read num

for((i=0; i<$num; i++))
do
	for((j=i; j>=0; j--))
	do
		echo -n "$j ";
	done
	echo
done


#0 
#1 0 
#2 1 0 
#3 2 1 0 
#4 3 2 1 0 
#5 4 3 2 1 0 
#6 5 4 3 2 1 0 
#7 6 5 4 3 2 1 0 
#8 7 6 5 4 3 2 1 0 
#9 8 7 6 5 4 3 2 1 0 

